Darknet interactie, tests, dockerfile waarmee je kan testen
Redoublet-org/Redoublet-card-detection pull request #2
Opened 2023-02-23 13:41 UTC by TheGoldenFyre

Added a testing framework to the project and added unit tests for all of the datastructure classes.

2023-03-08 10:57 UTC, TheGoldenFyre commented
Dus, functionaliteit: Darknet is een applicatie waarmee modellen zowel getraind kunnen worden als gebruikt kunnen worden voor detectie. Darknet.cs is een wrapper die de applicatie aanroept met gegeven een model in darknetconfig.txt (deze zul je lokaal aan moeten passen als je wilt testen, of laat de docker container het voor je doen). 

De ASP.Net API maakt gebruik van deze wrapper om detecties te doen; als input neemt het via /api/detect-card een base64 image, die vervolgens wordt opgeslagen. De file path hiervan wordt meegegeven aan de darknet applicatie; resultaten worden vervolgens uitgelezen uit de console. Dit wordt vervolgens weer teruggestuurd naar de aanvrager in de vorm van een json object.

Dockerfile is er om zowel darknet te installeren (wat een heel gedoe op zich is, als je het kan vermijden zou ik aanraden om het nooit handmatig op je pc te installeren), het model te downloaden van github, en vervolgens asp.net te installeren. Programma wordt daarna gebuild en gerund binnen docker op port 5050. Kan gewoon via de bekende commands `docker-compose build`, `docker-compose up`.

Verdere vragen worden zeker gewaardeerd! Dit hele stuk code is chaos en ik zal vast iets vergeten zijn neer te zetten.
Final note: tijdens het initalizeren van darknet geeft ie een aantal errors dat ie images niet kan vinden; dit beïnvloed de functionaliteit niet, dus heb ik het er maar in laten staan.

2023-03-13 09:40 UTC, rubenfranquinet requested changes
Ziet er nice uit. Zou je nog ergens (wellicht een readme) kunnen toevoegen welk format de input string voor de api requests moet hebben?

2023-03-13 09:40 UTC, rubenfranquinet commented on card-detection-api/docker-compose.yml
> +      - "5050:80"
Voeg een lege regel toe aan einde van de file.

2023-03-13 09:40 UTC, rubenfranquinet commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +            byte[] image = Convert.FromBase64String(jemoeder);
Ehmm bijzondere variabele naam. misschien even veranderen.

2023-03-13 09:40 UTC, rubenfranquinet commented on card-detection-api/card-detection-api/Darknet.cs
> +                //Console.Write(((char)c).ToString());
Nitpick: verwijder comments

2023-03-13 13:55 UTC, rubenfranquinet approved these changes

2023-03-13 13:55 UTC, rubenfranquinet commented on card-detection-api/Dockerfile
>  ENTRYPOINT ["dotnet", "card-detection-api.dll"]
new line aan einde :)

2023-03-13 13:55 UTC, rubenfranquinet commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> -}
new line :)

2023-03-13 13:55 UTC, rubenfranquinet commented on card-detection-api/card-detection-api/Properties/launchSettings.json
> +}
new line

2023-03-13 13:55 UTC, rubenfranquinet commented on card-detection-api/card-detection-tests/Properties/Resources.resx
> +</root>
New line

2023-03-13 13:55 UTC, rubenfranquinet commented on card-detection-api/docker-compose.yml
> +
nog eentje dan

2023-03-13 15:08 UTC, Koekiemonster69 approved these changes
Netjes gedaan! Was even worstelen maar ik snap t nu een stuk beter

2023-03-13 15:21 UTC, merged