Added CI/CD
Redoublet-org/Redoublet-card-detection pull request #3
Opened 2023-03-27 10:01 UTC by MatthijsdeHeus

CI/CD pipeline toegevoegd.
Resultaat wordt via Docker gehost op https://backend-rfvwfcxdeq-ez.a.run.app. (Swagger pagina is niet zichtbaar op productie)

Zie https://console.cloud.google.com/cloud-build/builds;region=global/b6151279-3fea-4f55-8e1b-6f41dca6a8b0?authuser=1&project=redoublet-card-detection

2023-03-27 10:31 UTC, Koekiemonster69 requested changes
wat moet ik precies hieraan reviewen?

2023-03-27 13:17 UTC, MatthijsdeHeus commented on cloudbuild.yaml
Als het goed is zou je dan niks moeten kunnen zien inhoudelijk?

2023-03-27 13:20 UTC, MatthijsdeHeus commented on cloudbuild.yaml
Je kan kijken naar de Cloud Build Trigger settings, en de settings van Cloud Run die aangeroepen worden.

2023-04-05 08:45 UTC, Toine1404 approved these changes

2023-04-20 12:50 UTC, Koekiemonster69 approved these changes
Volgens mij werkt het

2023-04-25 10:29 UTC, merged

2023-04-25 10:29 UTC, TheGoldenFyre commented
Staat al 3 weken open + hebben al meer mensen naar gekeken dan hier staat