Feature 223: Nieuwe model backend
Redoublet-org/Redoublet-card-detection pull request #5
Opened 2023-05-18 21:09 UTC by TheGoldenFyre

YOLOV8 support is toegevoegd aan de backend. Er is een nieuwe wrapper geschreven zodat er in C# detectieresultaten kunnen worden ingelezen, en er is een klein python scriptje toegevoegd dat het daadwerkelijke model aanroept.

NOTE: het uiteindelijke model zit hier nog NIET in! Ik heb een tijdelijk model toegevoegd dat wel kaarten detecteert, maar gwn niet zo denderend werkt. 

Reviewen kan door het project lokaal te draaien via visual studio (zorg er dan wel voor dat je python geinstalleerd hebt en `pip install ultralytics` runt voor de benodigde package), of door docker-compose te runnen. Het zou als drop-in solution moeten werken, dus je request en response format zijn niet aangepast.

2023-05-25 13:33 UTC, Koekiemonster69 approved these changes
Ziet er goed uit, detectie werkt een stuk beter nu! Ik moet eerlijk zeggen dat ik naar de code niet heel precies kon kijken, dit is gewoon technisch ver boven mijn niveau. Enige aanmerking die ik heb is om bij de documentatie van deze pr te zetten dat dit moet worden aangepast 
![image](https://github.com/Redoublet-org/Redoublet-card-detection/assets/74185498/ea9cac40-d597-4aa7-b977-f6ce9ac1e613)
in de file viewhandpage.vue, dat maakt t wellicht iets duidelijker

2023-05-31 13:56 UTC, rjvandel commented
double confidence = double.Parse(args[1], CultureInfo.InvariantCulture);
<3

2023-06-01 11:35 UTC, rjvandel requested changes
Zie mn comments. Ziet er voor mij abracadabra uit, dus misschien niet superrr nuttige review, vertrouw jou compleet haha...

2023-06-01 11:35 UTC, rjvandel commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +using Redoublet_backend.DetectionWrappers;
wordt dit gebruikt?

2023-06-01 11:35 UTC, rjvandel commented on card-detection-api/card-detection-api/DetectionWrappers/YOLOV8Wrapper.cs
> +using System.Security.Cryptography;
wordt dit gebruikt?

2023-06-01 11:35 UTC, rjvandel commented on card-detection-api/card-detection-api/Program.cs
> +using System;
Bovenste drie gebruikt?

2023-06-04 14:34 UTC, rjvandel approved these changes
noiceeee

2023-06-04 16:59 UTC, Koekiemonster69 approved these changes

2023-06-04 17:04 UTC, merged