Feature 261: detectie omstandigheden
Redoublet-org/Redoublet-card-detection pull request #6
Opened 2023-05-27 21:41 UTC by tvdplas

De eerste 3 van de 5 detectieomstandigheden in het [onderzoeksdocument](https://docs.google.com/document/d/1KnJtfYM_6QOBDVmtJaQrQ88twKirqPI4oJYdLTC9Bfo/edit?usp=sharing) zijn geïmplementeerd. De twee die niet geïmplementeerd zijn lijken me op het moment niet echt haalbaar, dus die heb ik maar even gelaten voor wat het is.

De omstandigheden zijn vervolgens toegevoegd aan het API resultaat, zodat de app hier mogelijk mee kan gaan werken.

Wat moet er getest worden: 
- Checken of je daadwerkelijk de properties in het resultaat kan zien (ik zou hiervoor een request met Postman aanraden)
- Testen met een aantal foto's om te zien of de waardes van de omstandigheden een beetje overeen komen met de verwachting

Hoe kan je testen:
- `docker-compose build` en `docker-compose up` runnen om een lokaal runnende versie van de API te krijgen op `http://localhost:5050/api/detect-card`. 
- Hier vervolgens met Postman een post request naar sturen, waarbij je body een raw json string is met base64 encoded image data (ik kan [deze site](https://codebeautify.org/image-to-base64-converter) aanraden als je snel wat testdata wilt genereren)
- Kijken of de requests doen wat er verwacht wordt.

2023-06-04 19:01 UTC, Stayutazen requested changes
Mooie code! Handige manier van werken om eerst je plan van aanpak uit te werken in het document! Alleen nog een paar kleine comments :)

2023-06-05 08:35 UTC, tvdplas commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +            _stopwatch.Restart();
Omdat het op google cloud best lastig is om debug output te zien lijkt het me wel lastig om het op deze manier erin te houden, dan kan je ook via de app zien hoe lang een detectie heeft geduurd

2023-06-05 08:50 UTC, tvdplas commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +            dr.Properties = DetectionPropertyService.All(image, dr.Detections);
Heb het gefixed door een groot deel van de logica naar de wrapper te halen.

2023-06-05 08:51 UTC, tvdplas commented on card-detection-api/card-detection-api/Services/DetectionPropertyService.cs
> +        /// <summary>r
lol :3

2023-06-05 08:51 UTC, tvdplas commented on card-detection-api/card-detection-api/Services/DetectionPropertyService.cs
> +                        return Models.Exposure.Proper;
omgedraaid

2023-06-05 16:35 UTC, Stayutazen requested changes
Het is best wel slay geworden

2023-06-05 16:35 UTC, Stayutazen commented on card-detection-api/card-detection-api/DetectionWrappers/YOLOV8Wrapper.cs
> +            currentResult.FileName = currentImgPath;
currentResult's filename wordt al geset bij setup
```suggestion
            
```

2023-06-05 16:35 UTC, Stayutazen commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
>              return dr;
detectionResult :)

2023-06-05 16:38 UTC, Stayutazen commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +            _stopwatch.Restart();
Snap ik maar ik zou het niet weergeven aan de gebruiker!

2023-06-05 16:49 UTC, Stayutazen approved these changes

2023-06-12 10:13 UTC, rjvandel approved these changes
Werkt!

2023-06-12 10:18 UTC, merged