Overlapping
Redoublet-org/Redoublet-card-detection pull request #8
Opened 2023-06-06 07:30 UTC by rjvandel

Nu met de nieuwe main + gefixte comments van Thomas

2023-06-06 09:32 UTC, tvdplas requested changes

2023-06-06 09:32 UTC, tvdplas commented on card-detection-api/card-detection-api/Controllers/DetectionController.cs
> +            return newDr;
Lijst aan detecties wordt direct aangepast door filterOverlaps, dus newDr == dr.

2023-06-19 08:22 UTC, Koekiemonster69 approved these changes
Niet kunnen testen, want ionic doet t niet bij mij, maar code ziet er goed uit 👍

2023-06-19 08:22 UTC, Koekiemonster69 commented on card-detection-api/card-detection-api/Models/Detection.cs
> +
Documentation comment zou heel nice zijn

2023-06-19 08:22 UTC, Koekiemonster69 commented on card-detection-api/card-detection-api/Models/Detection.cs
> +
Documentation comment zou heel nice zijn

2023-06-19 09:04 UTC, tvdplas submitted a review, later dismissed

2023-06-22 09:05 UTC, closed without merging